### ISSUE TITLE
Cannot compile template on JDK9

### ISSUE THREAD

**Issue by tdiesler** [mvel/mvel#106]
Seen on JDK9-ea137

```
Caused by: java.lang.ExceptionInInitializerError
	at org.mvel2.templates.TemplateCompiler.captureOrbToken(TemplateCompiler.java:305)
	at org.mvel2.templates.TemplateCompiler.compileFrom(TemplateCompiler.java:114)
	at org.mvel2.templates.TemplateCompiler.compile(TemplateCompiler.java:82)
	at org.mvel2.templates.TemplateCompiler.compileTemplate(TemplateCompiler.java:360)
	at org.apache.camel.component.mvel.MvelEndpoint.onExchange(MvelEndpoint.java:115)
	at org.apache.camel.impl.ProcessorEndpoint$1.process(ProcessorEndpoint.java:71)
	at org.apache.camel.util.AsyncProcessorConverterHelper$ProcessorToAsyncProcessorBridge.process(AsyncProcessorConverterHelper.java:61)
	... 163 more
Caused by: java.lang.NumberFormatException: For input string: "9-e"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(java.base@9-ea/FloatingDecimal.java:2054)
	at jdk.internal.math.FloatingDecimal.parseDouble(java.base@9-ea/FloatingDecimal.java:110)
	at java.lang.Double.parseDouble(java.base@9-ea/Double.java:539)
	at org.mvel2.util.ParseTools.<clinit>(ParseTools.java:84)
	... 170 more
```

CrossRef: https://github.com/wildfly-extras/wildfly-camel/issues/1340

**Comment by psiroky** [comment]
@tdiesler could you please specify the version you are using? Mvel `2.3.0.Final`+ _should_ be compatible with JDK 9 (or at least it was few months back).

**Comment by tdiesler** [comment]
camel-2.18.x currently uses mvel [2.3.1.Final](https://github.com/apache/camel/blob/master/parent/pom.xml#L441)

**Comment by tdiesler** [comment]
Yes, this was caused by an invalid usage of camel-2.17.x

**Comment by psiroky** [comment]
Great, thanks for the confirmation @tdiesler.
