### ISSUE TITLE
StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by andreisobchuck** [mvel/mvel#108]
`MVEL.compileExpression("1.0/25 or 1.0", new ParserContext());`
produces some result.

But

`MVEL.compileExpression("1.0/25 and 1.0", new ParserContext());`
gives StringIndexOutOfBoundsException:

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(String.java:1871)
    at org.mvel2.util.ErrorUtil.rewriteIfNeeded(ErrorUtil.java:17)
    at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:295)
    at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:52)
    at org.mvel2.MVEL.compileExpression(MVEL.java:810)
```
I think that both cases have incorrect behavior.

**Comment by lthuot** [comment]
Encountered the same problem. The exception occurs when outputing a CompileException (so it might occur in the logging system after the original exception is thrown). In the following code, if cursor is not less than end then matchStart will be -1 and the code will try to extract a substring of size expr.length + 1 from expr, which is invalid.
Code from CompileException.java: 
    int **matchStart = -1**;
    int matchOffset = 0;
    String match = null;
    if (cursor < end) {
      matchStart = cursor;
      if (matchStart > 0) {
        while (matchStart > 0 && !isWhitespace(expr[matchStart - 1])) {
          matchStart--;
        }
      }
      matchOffset = cursor - matchStart;
      match = new String(expr, matchStart, **expr.length - matchStart**);

**Comment by lichtin** [comment]
Can still cause an issue:
```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.<init>(String.java:192)
	at org.mvel2.CompileException.showCodeNearError(CompileException.java:155)
	at org.mvel2.CompileException.generateErrorMessage(CompileException.java:225)
	at org.mvel2.CompileException.toString(CompileException.java:68)
```

**Comment by lthuot** [comment]
@lichtin do you have a test case to reproduce it?
The case above ("1.0/25 and 1.0") yields a relevant exception in 2.4.2.Final:
"Error: was expecting type: java.lang.Boolean; but found type: java.lang.Double"
Some protection regarding negative cursor value might be introduced in CompileException.showCodeNearError() but having a test case to confirm the issue and the fix would be useful.
