### ISSUE TITLE
Compilation Exception - ArrayIndexOutOfBoundsException with a FOR in the IF 

### ISSUE THREAD

**Issue by rodolfobarbeiro** [mvel/mvel#110]
Hi,

I use MVEL for a few years and now I found a problem when a FOR loop it's inside IF.

Example of expression with cause the exception:

```java
List list1 = [1,2,3,4,5,6,7,8];
List list2 = new ArrayList();

if (list1 != null) {
   for(int item : list1) {
      list2.add(item);
   }
}
```

The expression without IF, work's fine:

```java
List list1 = [1,2,3,4,5,6,7,8];
List list2 = new ArrayList();

for(int item : list1) {
   list2.add(item);
}
```

Log msg:

```
org.mvel2.CompileException: [Error: unexpected end of statement]
[Near : {... ist1) { ....}]
                    ^
[Line: 10, Column: 13]
        at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1292)
at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1292)
        at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:111)
        at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:52)
        at org.mvel2.MVEL.compileExpression(MVEL.java:810)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 168
        at org.mvel2.compiler.AbstractParser.ifThenElseBlockContinues(AbstractParser.java:1787)
        at org.mvel2.compiler.AbstractParser.captureCodeBlock(AbstractParser.java:1604)
        at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:433)
        ... 47 common frames omitted
```

I tested in versions 2.2.7 and 2.3.1 and the same problem occurred

**Comment by VadimSharomov** [comment]
I have the same result (exactly the same exception) when I used 'if' operator at the end of expression. I use it as expressions in xml-based configurations in Apache Camel 2.17.1.

There is some test code located at the end of expression:
```
if (1 > 0) {
    System.out.println("1 > 0 = " + (1 > 0));
}
```
 It gives this exception:

```
Caused by: org.mvel2.CompileException: [Error: unexpected end of statement]
[Near : {... stem.out.println("1 > 0 = " + (1 > 0)); ....}]
                                                    ^
[Line: 96, Column: 9]
 	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1299)
at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:81)
 	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:47)
 	at org.mvel2.MVEL.eval(MVEL.java:165)
at com.tonicforhealth.integration.platform.expression.ExpressionEvaluator.evaluate(ExpressionEvaluator.java:41)
 	... 89 common frames omitted
 Caused by: java.lang.ArrayIndexOutOfBoundsException: 4623
 	at org.mvel2.compiler.AbstractParser.ifThenElseBlockContinues(AbstractParser.java:1794)
 	at org.mvel2.compiler.AbstractParser.captureCodeBlock(AbstractParser.java:1611)
 	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:440)
 	... 93 common frames omitted

```


If I put any operator behind if-operator, then it works fine!

```
if (1 > 0) {
    System.out.println("1 > 0 = " + (1 > 0));
}
a = 1;
```
I tested that case in different my configurations. It leads the same result.
If only If-operator located at the end of expression - it gives this exception.

If there is another operator than 'If(){}' then it works fine without any exceptions.
