### ISSUE TITLE
PropertyAccessException on second run of compiled expression with null safe operator and whitespace

### ISSUE THREAD

**Issue by jdomigon** [mvel/mvel#141]
Hi, we've detected a problem when reusing a compiled expression involving the null safe operator and whitespace or parenthesis:

If the expression is like `"?bean.?value == \"a\""` it's evaluation and reevaluation is ok.

But if the expression is like `" ?bean.?value == \"a\""` or `"(?bean.?value == \"a\")"`, the first evaluation succeeeds, but the second one fails with a PropertyAccessException on a trimmed-down property (**valu** in this case:

```
[Error: could not access: valu; in class: org.mvel2.tests.core.NullSafeTest$Reg1]
[Near : {... (?bean.?value) ....}]
                    ^
[Line: 1, Column: 8]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:706)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:360)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:163)
	at org.mvel2.optimizers.impl.refl.nodes.NullSafe.getValue(NullSafe.java:27)
	at org.mvel2.optimizers.impl.refl.nodes.VariableAccessor.getValue(VariableAccessor.java:37)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.Substatement.getReducedValueAccelerated(Substatement.java:44)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.MVEL.executeExpression(MVEL.java:968)
```
Funnily enough, adding more whitespace or parenthesis prepended to the sentence seems to trim down even more the property access. Expressions like `"  ?bean.?value == \"a\""` or `"((?bean.?value == \"a\"))"`, fail with an incorrect access to **val** property:

```
[Error: could not access: val; in class: org.mvel2.tests.core.NullSafeTest$Reg1]
[Near : {... ((?bean.?value)) ....}]
                     ^
[Line: 1, Column: 9]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:706)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:360)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:163)
	at org.mvel2.optimizers.impl.refl.nodes.NullSafe.getValue(NullSafe.java:27)
	at org.mvel2.optimizers.impl.refl.nodes.VariableAccessor.getValue(VariableAccessor.java:37)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.Substatement.getReducedValueAccelerated(Substatement.java:44)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.Substatement.getReducedValueAccelerated(Substatement.java:44)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.MVEL.executeExpression(MVEL.java:968)
```
I attach a testcase reproducing the issue:
[NullSafeTest.zip](https://github.com/mvel/mvel/files/1653217/NullSafeTest.zip)

Issue  #115 could be related. This test case seems simpler, though.

**Comment by NoelAranha** [comment]
Is there any active work going on for this ticket or for #115?
