### ISSUE TITLE
Add more than 10 items to an mvel list with ASM Opitmizer crashes

### ISSUE THREAD

**Issue by milosimpson** [mvel/mvel#145]
Seems to only happen with the ASM Optimizer.   Can work-around the issue by explicitly using a `java.util.ArrayList`.

Included here is a test case/class that demonstrates the issue.

We are "stuck" on mvel version `2.2.2.Final`, and the issue is reproducible against the latest version `2.4.0.Final`.

```java
package test.rules;

import org.mvel2.MVEL;
import org.mvel2.integration.VariableResolverFactory;
import org.mvel2.integration.impl.MapVariableResolverFactory;
import org.mvel2.optimizers.OptimizerFactory;
import org.testng.Assert;
import org.testng.annotations.Test;
import java.io.Serializable;
import java.util.HashMap;

import static org.mvel2.MVEL.executeExpression;

/**
 * Test that demonstrates the Mvel issue.
 *
 * Software we use embeds MVEL and sets the default optimizer to ASM
 *  - OptimizerFactory.setDefaultOptimizer("ASM");
 *
 * If we create a list in Mvel and add more than 10 items to it, then
 *  "bad things happen" / it throws an Exception.
 *
 * We are able to work around this by explicitly creating an ArrayList.
 *
 * Workaround :
 *   FROM : list = [];
 *     TO : list = new java.util.ArrayList();
 */
@Test
public class MvelArrayTest {

    // Add more than 10 items to an mvel list, where we sometimes add null.
    // Then use java.util.Collections to replace all nulls with a default value
    // and use Collections.max to find the biggest value
    private final String biglistTestScript =
        "list = [];\n" +
        "list.add(1);\n" +
        "list.add(2);\n" +
        "list.add(3);\n" +
        "list.add(null);\n" + // null!
        "list.add(5);\n" +
        "list.add(6);\n" +
        "list.add(7);\n" +
        "list.add(8);\n" +
        "list.add(9);\n" +
        "list.add(10);\n" +
        "list.add(11);\n" +
        "list.add(12);\n" +
        "java.util.Collections.replaceAll( list, null, 25 );\n" + // replace nulls, with a big value
        "java.util.Collections.max( list );\n";  // return

    /**
     * Demonstrate the error.
     *
     * FYI this is what the stacktrace looks like when the error occurs.
     *
     *
        [Error: list = [];
        list.add(1);
        list.add(2);
        list.add(3);
        list.add(null);
        list.add(5);
        list.add(6);
        list.add(7);
        list.add(8);
        list.add(9);
        list.add(10);
        list.add(11);
        list.add(12);
        java.util.Collections.replaceAll( list, null, 25 );
        java.util.Collections.max( list );
        ]
        [Near : {... list = []; ....}]
                     ^
        [Line: 1, Column: 1]

            at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:860)
            at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:245)
            at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
            at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
            at org.mvel2.MVELRuntime.execute(MVELRuntime.java:86)
            at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
            at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
            at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:113)
            at org.mvel2.MVEL.executeExpression(MVEL.java:942)
            at test.rules.MvelArrayTest.demonstrate_AsmOptimizerDiesWithBigList(MvelArrayTest.java:55)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
            at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
            at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
            at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
            at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
            at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
            at org.testng.TestRunner.privateRun(TestRunner.java:767)
            at org.testng.TestRunner.run(TestRunner.java:617)
            at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
            at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
            at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
            at org.testng.SuiteRunner.run(SuiteRunner.java:240)
            at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
            at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
            at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
            at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
            at org.testng.TestNG.run(TestNG.java:1031)
            at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
            at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
        Caused by: java.lang.reflect.InvocationTargetException
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:498)
            at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.getMethod(ASMAccessorOptimizer.java:2156)
            at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:759)
            ... 32 more
        Caused by: java.lang.NullPointerException
            at java.util.Collections.max(Collections.java:673)
            ... 38 more
     */
    @Test(expectedExceptions = org.mvel2.PropertyAccessException.class)
    public void demonstrate_AsmOptimizerDiesWithBigList() {

        OptimizerFactory.setDefaultOptimizer("ASM");
        Serializable compileExpression = MVEL.compileExpression( biglistTestScript );
        VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap());

        executeExpression(compileExpression, factory);
        Assert.fail( "If we got here, then the issue was fixed and this test should go away!" );
    }



    /////
    // Show that the other Optimizer types don't have this problem.
    //
    @Test
    public void demonstrate_reflectiveOptimizerWorksFine() {

        OptimizerFactory.setDefaultOptimizer("reflective");
        Serializable compileExpression = MVEL.compileExpression( biglistTestScript );
        VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap());

        int actual = (int) executeExpression(compileExpression, factory);
        Assert.assertEquals( actual, 25);
    }

    @Test
    public void demonstrate_dynamicOptimizerWorksFine() {

        OptimizerFactory.setDefaultOptimizer("dynamic");
        Serializable compileExpression = MVEL.compileExpression( biglistTestScript );
        VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap());

        int actual = (int) executeExpression(compileExpression, factory);
        Assert.assertEquals( actual, 25);
    }


    ////
    // Show that adding less then 10 things to the list works fine
    //
    // Less than 10 items is fine
    private final String smallListTestScript =
        "list = [];\n" +
        "list.add(1);\n" +
        "list.add(2);\n" +
        "list.add(3);\n" +
        "list.add(null);\n" + // null!
        "list.add(5);\n" +
        "list.add(6);\n" +
        "java.util.Collections.replaceAll( list, null, 25 );\n" + // replace nulls, with a big value
        "java.util.Collections.max( list );\n";  // return

    @Test
    public void demonstrate_AsmOptimizerWithSmallListIsFine() {

        OptimizerFactory.setDefaultOptimizer("ASM");
        Serializable compileExpression = MVEL.compileExpression( smallListTestScript );
        VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap());

        int actual = (int) executeExpression(compileExpression, factory);
        Assert.assertEquals( actual, 25);
    }
}
```

**Comment by gogainda** [comment]
What's the benefit  of using ASM optimizer here?

**Comment by milosimpson** [comment]
Cool.   Closing this ticket.   One suggestion tho, change the test name from "AsmOptimizerDiesWithBigList"   to something like   "AsmOptimizerWorkWithBigList".
