### ISSUE TITLE
Compilation error when use Java Lambda Functions has parameter

### ISSUE THREAD

**Issue by rodolfobarbeiro** [mvel/mvel#148]
Compile error occurs when using lambda function as in the example below. The funcion _map(entry -> entry.getKey())_ cause the error. Replacing function to _map(Entry::Key)_ causes the same error.

Expression with error:

```
values = ["A":1, "B":1, "C":1, "D":1, "E":1, "F":1, "G":1, "H":1];
firstValues = values.entrySet().stream().limit(5).map(entry -> entry.getKey()).collect(java.util.stream.Collectors.toList());
return firstValues;
```

Error:

```
java.lang.RuntimeException: Malformed expression
	at org.mvel2.util.ASTBinaryTree.getReturnType(ASTBinaryTree.java:35)
	at org.mvel2.util.ASTBinaryTree.getReturnType(ASTBinaryTree.java:36)
	at org.mvel2.util.CompilerTools.getReturnType(CompilerTools.java:358)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:284)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:52)
	at org.mvel2.MVEL.analyze(MVEL.java:680)
	at org.mvel2.compiler.PropertyVerifier.getMethod(PropertyVerifier.java:526)
	at org.mvel2.compiler.PropertyVerifier.analyze(PropertyVerifier.java:120)
	at org.mvel2.compiler.ExpressionCompiler.verify(ExpressionCompiler.java:373)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:266)
	at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2059)
	at org.mvel2.ast.AssignmentNode.<init>(AssignmentNode.java:69)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:863)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:111)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:52)
	at org.mvel2.MVEL.compileExpression(MVEL.java:810)
```

**Comment by ruchichhabra009** [comment]
Any update on this, if we can use lambdas in MVELCondition?

**Comment by mariofusco** [comment]
mvel doesn't and won't support Java 8 style lambdas.

**Comment by j-razeed** [comment]
It's been 2 years. Is there any roadmap to implement the feature (Java 8 style lambdas)?
