### ISSUE TITLE
IllegalAccessError when MVEL tries to access HeapByteBuffer class

### ISSUE THREAD

**Issue by salonirmehta** [mvel/mvel#161]
I am stuck with the below issue:

Getting the below exception when MVEL executes an expression:

```
java.lang.IllegalAccessError: tried to access class java.nio.HeapByteBuffer from class ASMAccessorImpl_2330495751530608772190
    at ASMAccessorImpl_2330495751530608772190.getValue(Unknown Source)
    at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:79)
    at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
    at org.mvel2.MVELRuntime.execute(MVELRuntime.java:86)
    at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
    at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
    at org.mvel2.MVEL.executeExpression(MVEL.java:922)
```

Wanted to highlight that -> We are compiling expressions on a different JVM and executing it on another JVM. Does this impact MVEL?

Any help on this is appreciated.

**Comment by MalcolmOdd** [comment]
Calling OptimizerFactory.setDefaultOptimizer(OptimizerFactory.SAFE_REFLECTIVE) prior to evaluating expressions might resolve this.
Can you provide expression and context?
My guess is it could be caused by the fact that HeapByteBuffer has package scope but you're probably trying to call a method declared in the public parent class ByteBuffer or Buffer. This would be fixed by https://github.com/mvel/mvel/pull/184.
