### ISSUE TITLE
method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool

### ISSUE THREAD

**Issue by b-vesco** [mvel/mvel#162]
Using ```+--- org.mvel:mvel2:2.4.0.Final```

```
**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/MVEL
Expression: @comment{'A template @DataObject that creates cheatsheets doc'}@includeNamed{'common-lib.templ'}@code{                                                                                                                                                                   def renderTagLinkToHtml(tag) {    return tag.name;  }                                                         def getDataType(type) {    var kind = type.kind;    if (kind.basic) {      if (kind == CLASS_STRING) {        return 'String';      }      var typeName = type.name;      if (typeName == 'java.lang.Boolean' || typeName == 'boolean') {        return "Boolean";      }      if (typeName == 'java.lang.Character' || typeName == 'chat') {        return "Char";      }      if (typeName == 'java.lang.Byte' || typeName == 'byte' ||          typeName == 'java.lang.Short' || typeName == 'short' ||          typeName == 'java.lang.Integer' || typeName == 'int' ||          typeName == 'java.lang.Long' || typeName == 'long' ||          typeName == 'java.lang.Float' || typeName == 'float' ||          typeName == 'java.lang.Double' || typeName == 'double') {        return 'Number (' + type.simpleName + ')';      }    } else if (kind == CLASS_JSON_OBJECT) {      return 'Json object';    } else if (kind == CLASS_JSON_ARRAY) {      return 'Json array';    } else if (kind == CLASS_DATA_OBJECT) {      return 'link:dataobjects.html#' + type.raw.simpleName + '[' + type.raw.simpleName + ']';    } else if (kind == CLASS_ENUM) {      return 'link:enums.html#' + type.raw.simpleName + '[' + type.raw.simpleName + ']';    } else if (kind == CLASS_API) {      if (type.name == 'io.vertx.core.buffer.Buffer') {        return "Buffer"      }    }    System.out.println("unhandled type " + type);    return null;  }}[[@{type.simpleName}]]
== @{type.simpleName}

@if{doc != null}++++
@{renderDocToHtml('', doc, renderTagLinkToHtml)}++++
'''
@end{}
[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
@foreach{property:properties}@code{propertyType=getDataType(property.type)}@code{arrayPrefix = (property.list || property.set) ? 'Array of ' : ''}@if{propertyType != null}|[[@{property.name}]]`@{property.name}`|`@{arrayPrefix}@{getDataType(property.type)}`|@if{property.doc != null}
+++
@{renderDocToHtml('', property.doc, renderTagLinkToHtml).trim()}
+++
@else{}-
@end{}@end{}@end{}|===
```

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':annotationProcessing'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.RuntimeException: java.lang.VerifyError: (class: ASMAccessorImpl_81800112415312699307878, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:158)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:96)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:90)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:50)
        at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:86)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:47)
        at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:33)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:40)
        at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:27)
        at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:161)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:146)
        at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:118)
        at jdk.internal.reflect.GeneratedMethodAccessor971.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more
Caused by: java.lang.VerifyError: (class: ASMAccessorImpl_81800112415312699307878, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:757)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:891)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:279)
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95)
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
        at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
        at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
        at org.mvel2.ast.IndexedAssignmentNode.getReducedValueAccelerated(IndexedAssignmentNode.java:118)
        at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
        at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
        at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
        at org.mvel2.ast.Function.call(Function.java:165)
        at org.mvel2.ast.PrototypalFunctionInstance.call(PrototypalFunctionInstance.java:18)
        at org.mvel2.optimizers.impl.refl.nodes.FunctionAccessor.getValue(FunctionAccessor.java:49)
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
        at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
        at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
        at org.mvel2.MVEL.executeExpression(MVEL.java:929)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:45)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:114)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CompiledNamedIncludeNode.eval(CompiledNamedIncludeNode.java:71)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:285)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:247)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:255)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:207)
        at org.mvel2.templates.res.CompiledNamedIncludeNode.eval(CompiledNamedIncludeNode.java:71)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
        at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:46)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:285)
        at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:247)
        at io.vertx.codegen.Template.render(Template.java:185)
        at io.vertx.codegen.CodeGenProcessor$GeneratedFile.generate(CodeGenProcessor.java:397)
        at io.vertx.codegen.CodeGenProcessor.lambda$process$8(CodeGenProcessor.java:323)
        at io.vertx.codegen.CodeGenProcessor.process(CodeGenProcessor.java:320)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:964)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:110)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:801)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1200)
        at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1333)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1250)
        at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:928)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
        at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
        ... 56 more```

**Comment by zregvart** [comment]
I think this was fixed with #159

**Comment by b-vesco** [comment]
Is it in a release I can try?
