### ISSUE TITLE
method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool

### ISSUE THREAD

**Issue by Nik-M-IW** [mvel/mvel#175]
Hi guys,

We are currently using smooks in a WSO2 custom message builder/ formatter that will read an EDI file from a folder and sets the WSO2 payload as the transformed xml.

Our WSO2ESB server has been receiving this error intermittently while trying to process larger EDI files using Smooks (30+ lines). Any assistance would be appreciated.

We are currently using:

- org.milyn.edi.unedifact:d01b-mapping:1.4
- wso2esb-5.0.0
- jdk-8u121-linux-x64
- mvel2-2.1.0.wso2v1

```
ERROR {org.wso2.carbon.connector.util.ResultPayloadCreate} -  Error while processing the file/folder {org.wso2.carbon.connector.util.ResultPayloadCreate}org.milyn.SmooksException: Failed to filter source. 
at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:86) 
at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:61) 
at org.milyn.Smooks._filter(Smooks.java:516) 
at org.milyn.Smooks.filterSource(Smooks.java:475) 
at works.in.extension.UNEdifactMessageBuilder.processDocument(UNEdifactMessageBuilder.java:50) 
at org.wso2.carbon.connector.util.ResultPayloadCreate.buildFile(ResultPayloadCreate.java:164) 
at org.wso2.carbon.connector.FileRead.connect(FileRead.java:83) 
at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32) 
at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:84) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) 
at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:104) 
at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:148) 
at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:84) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) 
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) 
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:97) 
at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:59) 
at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) 
at org.apache.synapse.core.axis2.ProxyServiceMessageReceiver.receive(ProxyServiceMessageReceiver.java:210) 
at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) 
at org.apache.synapse.startup.tasks.MessageInjector.execute(MessageInjector.java:321) 
at org.wso2.carbon.mediation.ntask.NTaskAdapter.execute(NTaskAdapter.java:98) 
at org.wso2.carbon.ntask.core.impl.TaskQuartzJobAdapter.execute(TaskQuartzJobAdapter.java:67) 
at org.quartz.core.JobRunShell.run(JobRunShell.java:213) 
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) 
at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
at java.lang.Thread.run(Thread.java:745)
Caused by: org.milyn.SmooksException: Error in 'org.milyn.javabean.BeanInstanceCreator' while processing the visitBefore event. 
at org.milyn.delivery.sax.SAXHandler.processVisitorException(SAXHandler.java:573) 
at org.milyn.delivery.sax.SAXHandler.processVisitorException(SAXHandler.java:559) 
at org.milyn.delivery.sax.SAXHandler.visitBefore(SAXHandler.java:311)
at org.milyn.delivery.sax.SAXHandler.startElement(SAXHandler.java:173) 
at org.milyn.delivery.SmooksContentHandler.startElement(SmooksContentHandler.java:67) 
at org.milyn.edisax.EDIParser.startElement(EDIParser.java:809) 
at org.milyn.edisax.EDIParser.mapSegment(EDIParser.java:514) 
at org.milyn.edisax.EDIParser.mapSegments(EDIParser.java:481) 
at org.milyn.edisax.EDIParser.mapSegments(EDIParser.java:488) 
at org.milyn.edisax.EDIParser.mapSegments(EDIParser.java:411) 
at org.milyn.edisax.EDIParser.parse(EDIParser.java:387) 
at org.milyn.edisax.EDIParser.parse(EDIParser.java:371) 
at org.milyn.edisax.unedifact.handlers.r41.UNHHandler.process(UNHHandler.java:80) 
at org.milyn.edisax.unedifact.handlers.r41.UNBHandler.process(UNBHandler.java:80) 
at org.milyn.edisax.unedifact.UNEdifactInterchangeParser.parse(UNEdifactInterchangeParser.java:98) 
at org.milyn.smooks.edi.unedifact.UNEdifactReader.parse(UNEdifactReader.java:77) 
at org.milyn.delivery.sax.SAXParser.parse(SAXParser.java:70) 
at org.milyn.delivery.sax.SmooksSAXFilter.doFilter(SmooksSAXFilter.java:75)
... 31 more
Caused by: java.lang.VerifyError: (class: ASMAccessorImpl_10938489911547072416460, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool 
at java.lang.Class.getDeclaredConstructors0(Native Method) 
at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671) 
at java.lang.Class.getConstructor0(Class.java:3075) 
at java.lang.Class.newInstance(Class.java:412) 
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:712) 
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeSetAccessor(ASMAccessorOptimizer.java:626) 
at org.mvel2.optimizers.dynamic.DynamicSetAccessor.optimize(DynamicSetAccessor.java:83) 
at org.mvel2.optimizers.dynamic.DynamicSetAccessor.setValue(DynamicSetAccessor.java:60) 
at org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:59) 
at org.mvel2.ast.DeepAssignmentNode.getReducedValueAccelerated(DeepAssignmentNode.java:94) 
at org.mvel2.MVELRuntime.execute(MVELRuntime.java:89) 
at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:128) 
at org.mvel2.MVEL.executeExpression(MVEL.java:928) 
at org.milyn.expression.MVELExpressionEvaluator.exec(MVELExpressionEvaluator.java:99) 
at org.milyn.expression.MVELExpressionEvaluator.exec(MVELExpressionEvaluator.java:115) 
at org.milyn.javabean.BeanInstanceCreator.createAndSetBean(BeanInstanceCreator.java:269) 
at org.milyn.javabean.BeanInstanceCreator.visitBefore(BeanInstanceCreator.java:214) 
at org.milyn.delivery.sax.SAXHandler.visitBefore(SAXHandler.java:302) 
... 46 more
```

**Comment by tbee** [comment]
I'm running into the same problem when upgrading an application from Java 8 (Oracle) to Java 12 (OpenJDK). I have upgraded relevant jars to the latest version, most notably mvel 2.4.4-Final (milyn-smooks 1.7.1 uses 2.2.4-Final, but 2.4.4 is configured explicitly). Any progess?

**Comment by tbee** [comment]
This problem seems to be duplicated here https://github.com/mvel/mvel/issues/159

**Comment by rratliff** [comment]
Because you said you ran into it when processing larger files, I am wondering if it is related to #189.
