### ISSUE TITLE
Cannot resolve variable when escaping orb @. unknown token type: $

### ISSUE THREAD

**Issue by Antoniossss** [mvel/mvel#176]
I am using version 2.4.0.Final and 
org.mvel2.templates.TemplateRuntime#eval; to evaluate templates

What I am doing:
Template of "${productPath}/${fileName}" evaluates fine to "somedir/here/filename.txt"
however template of
"release@${domainName}" as well as "release@@@${domainName}" raises exception

Caused by: java.lang.RuntimeException: unknown token type: $
  at org.mvel2.templates.TemplateCompiler.compileFrom(TemplateCompiler.java:238)
  at org.mvel2.templates.TemplateCompiler.compile(TemplateCompiler.java:82)
  at org.mvel2.templates.TemplateCompiler.compileTemplate(TemplateCompiler.java:348)
  at org.mvel2.templates.TemplateRuntime.eval(TemplateRuntime.java:103)

How to overcome this?

**Comment by Antoniossss** [comment]
Why I would try to escape @ with @@@ instead of @@ is a brainf*** to me.
