### ISSUE TITLE
java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor

### ISSUE THREAD

**Issue by rady66** [mvel/mvel#194]
In Mvel 2.4.3 on WildFly 16/Open JDK 11 we observe that
```

java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:718)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2245)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2254)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:750)
	at org.mvel//org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeSetAccessor(ASMAccessorOptimizer.java:665)
	at org.mvel//org.mvel2.optimizers.dynamic.DynamicSetAccessor.optimize(DynamicSetAccessor.java:83)
	at org.mvel//org.mvel2.optimizers.dynamic.DynamicSetAccessor.setValue(DynamicSetAccessor.java:60)
	at org.mvel//org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:59)
	at org.mvel//org.mvel2.ast.DeepAssignmentNode.getReducedValueAccelerated(DeepAssignmentNode.java:90)
	at org.mvel//org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel//org.mvel2.MVEL.executeExpression(MVEL.java:968)

```

**Comment by abykuruvilla-dev** [comment]
@rady66 Did you get a fix for this? I got a noclassdeffounderror while sharing CompiledTemplate between multiple threads. Looks like they do not thread-safe.

**Comment by MalcolmOdd** [comment]
@abykuruvilla-dev the code has changed a lot since this was reported. Can you send a recent stack trace? Also a code sample would be helpful. Also the following comment seems relevant (though is says it should be synchronized, it doesn't appear to be):
https://github.com/mvel/mvel/blob/9bac4ed85825ad4379fa8ed29aadd084b5c64ddf/src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java#L2327

**Comment by abykuruvilla-dev** [comment]
@MalcolmOdd sure. It strangely happens for certain templates and only after deployment. Because of company policy reasons I can't share the exact code.
But we use orbs and mostly like this
@{AmountValidation.isNonNegative(row.get("totalAmount"))}
We provide the context using VariableResolverFactory.
Attached the stacktrace 
```
Caused by: java.lang.NoClassDefFoundError: null
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603) ~[na:na]
... 72 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor
at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[na:na]
at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:878) ~[na:na]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2311) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2322) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:814) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:957) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:345) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.ast.Union.getReducedValueAccelerated(Union.java:39) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.MVEL.executeExpression(MVEL.java:945) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.templates.res.CompiledTerminalExpressionNode.eval(CompiledTerminalExpressionNode.java:39) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:285) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:247) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:255) ~[mvel2-2.4.12.Final.jar!/:na]
at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:203) ~[mvel2-2.4.12.Final.jar!/:na]
***********************remove private classes from stack trace***************************************
at java.base/java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1448) ~[na:na]
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]
Caused by: java.lang.ClassNotFoundException: org.mvel2.compiler.Accessor
at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:719) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[na:na]
... 33 common frames omitted
```

**Comment by MalcolmOdd** [comment]
Sorry, I tried to reproduce it with Oracle JDK8 and OpenJDk17 and could not (the code definitely went through ContextClassLoader.defineClass and I had numerous threads calling MVEL.executeExpression() on the same expression that was compiled with MVEL.compileExpression()).
Can you provide any additional details (OS, JDK, minimal code)?

**Comment by rady66** [comment]
that was pretty back in time so i forgot how we resolved it... it could be a synchronization/timing issue where classloader-s are reset and then reverted back... a code inspection might narrow down the problem while reproducing is quite difficult

**Comment by ptziegler** [comment]
I also ran into this problem a few days ago, where a similar exception was thrown while trying to load a certain _ASMAccessorImpl\_\<random-hash\>_ class. 

After taking a closer look, I was able to pinpoint the issue to the following line of code, similar to what MalcolmOdd already mentioned above.

https://github.com/mvel/mvel/blob/9bac4ed85825ad4379fa8ed29aadd084b5c64ddf/src/main/java/org/mvel2/optimizers/impl/asm/ASMAccessorOptimizer.java#L2329-L2332

The problem: Our context classloader is independent from our application, so the classloader that's calling MVEL is not the one that's used to load the class. Said classloader doesn't have MVEL in its classpath, leading to this error. The solution then simply consisted of explicitly adding MVEL to the context classloader.

**Comment by stefanofalconetti** [comment]
Hi Group, I'm running into the exact same issue but using Smooks

_t org.smooks.engine.delivery.sax.ng.SaxNgContentHandler.startElement(SaxNgContentHandler.java:186)
	at org.smooks.engine.delivery.SmooksContentHandler.startElement(SmooksContentHandler.java:110)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.smooks.engine.delivery.sax.ng.SaxNgParser.parse(SaxNgParser.java:87)
	at org.smooks.engine.delivery.sax.ng.SaxNgFilter.doFilter(SaxNgFilter.java:111)
	... 56 more
Caused by: java.lang.NoClassDefFoundError: org/mvel2/compiler/Accessor
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:874)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader.defineClass(ASMAccessorOptimizer.java:2321)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.loadClass(ASMAccessorOptimizer.java:2332)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:814)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeSetAccessor(ASMAccessorOptimizer.java:729)
	at org.mvel2.optimizers.dynamic.DynamicSetAccessor.optimize(DynamicSetAccessor.java:83)
	at org.mvel2.optimizers.dynamic.DynamicSetAccessor.setValue(DynamicSetAccessor.java:60)
	at org.mvel2.compiler.CompiledAccExpression.setValue(CompiledAccExpression.java:59)_

to try to do the same workaround until this is fixed I'm getting it is not the mvel ContextClassLoader (org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer$ContextClassLoader extends java.lang.ClassLoader) I would have to use, but my own class loader. Something looking like:


	              /**
			 * org/mvel2/compiler/Accessor
			 */
			ClassLoader contextClassLoader = Thread.currentThread().getContextClassLoader();
			try {
				contextClassLoader.loadClass(org.mvel2.compiler.Accessor.class.getName());
			} catch (ClassNotFoundException exc) {
				throw new ExceptionInInitializerError( exc);
			}


Since I'm in a multi threaded applications on top of SpringBoot, I will need to do this in each and every thread processing a request.

Did I get you right ?

If not, can you provide a sample of how you expect to have the whole mvel2 package loaded into the context class loader ?

Thanks,

Stefano.
