### ISSUE TITLE
MVEL is not able to compile grouped conditions

### ISSUE THREAD

**Issue by rroshan91** [mvel/mvel#230]
If I am using grouping in condition like `traffic = 10 || (traffic == 0 && (traffic in ('NA', 'A+', 'A', 'B+', 'B', 'B-', 'C+', 'C', 'C-') || traffic == \"NA\"))`, then MVEL is failing with unexpected token error.

Unit test to repro:
```
  @Test
  public void testMvelExpression() {
    // given
    String expression = "traffic >= 10 || (traffic == 0 && (traffic in ('NA', 'A+', 'A', 'B+', 'B', 'B-', 'C+', 'C', 'C-') || traffic == \"NA\"))";
    // when
    Serializable compiledExpression = MVEL.compileExpression(expression);
    // then
    assertNotNull(compiledExpression);
  }
```

Exception:
```
[Error: unexpected token: ]
[Near : {... traffic >= 10 || (traffic == 0 ....}]
             ^
[Line: 1, Column: 1]
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:263)
	at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2083)
	at org.mvel2.ast.Substatement.<init>(Substatement.java:38)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1132)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:126)
	at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2083)
	at org.mvel2.ast.Fold.<init>(Fold.java:75)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1048)
	at org.mvel2.compiler.AbstractParser.nextTokenSkipSymbols(AbstractParser.java:241)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:171)
	at org.mvel2.util.ParseTools.subCompileExpression(ParseTools.java:2083)
	at org.mvel2.ast.Substatement.<init>(Substatement.java:38)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1132)
	at org.mvel2.compiler.AbstractParser.nextTokenSkipSymbols(AbstractParser.java:241)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:171)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:67)
	at org.mvel2.MVEL.compileExpression(MVEL.java:810)
	at org.mvel2.MVEL.compileExpression(MVEL.java:819)
	at org.mvel2.MVEL.compileExpression(MVEL.java:723)
	at com.test.mvel.handlers.MVELTest.testMvelExpression(MVELTest.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

This is very common scenario.

**Comment by MalcolmOdd** [comment]
Hi @rroshan91 ,
I don't think this is a proper use of the "in" operator. See "Projections and folds" in http://mvel.documentnode.com. The parser would expect the part to the right of 'in' to be a list of objects and it would try to extract the 'traffic' property from each of them to create a new list.
I think your expressions should use the "contains" operator, as follows:
"traffic >= 10 || (traffic == 0 && (['NA', 'A+', 'A', 'B+', 'B', 'B-', 'C+', 'C', 'C-'] contains traffic || traffic==\"NA\"))".
