### ISSUE TITLE
Regression/backward compatibility break  in 2.4.14 with regard to null mbehaviour

### ISSUE THREAD

**Issue by flozano** [mvel/mvel#293]
This code used to work in 2.4.13 but stopped working in 2.4.14: 
```java
package mvel2.tests;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.hamcrest.core.IsInstanceOf.instanceOf;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;

import java.util.HashMap;

import org.junit.Test;
import org.mvel2.MVEL;
import org.mvel2.ParserContext;

public class MvelBehaviourTest {

	@Test
	public void testDoubleWithNull() {
		var context = new ParserContext();
		context.addInput("v1", Double.class);
		context.addInput("v2", Double.class);

		var compiled = MVEL.compileExpression("v1 * v2", context);
		var input = new HashMap<Object, Object>();
		input.put("v1", null);
		input.put("v2", 4d);
		var result = MVEL.executeExpression(compiled, input);
		assertNotNull(result);
		assertThat(result, instanceOf(Boolean.class));
		assertEquals(false, result);
	}
}
```

in 2.4.14, I get:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Number.doubleValue()" because "val" is null
	at org.mvel2.math.MathProcessor.toDouble(MathProcessor.java:657)
	at org.mvel2.math.MathProcessor.doOperationsSameType(MathProcessor.java:533)
	at org.mvel2.math.MathProcessor._doOperations(MathProcessor.java:210)
	at org.mvel2.math.MathProcessor.doOperations(MathProcessor.java:78)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:145)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:985)
	at mvel2.tests.MvelBehaviourTest.testDoubleWithNull(MvelBehaviourTest.java:26)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:93)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

It's a hotfix version change but it can break easily any DRL rule that expected this behaviour. I actually like the new behaviour better, but it's not backward-compatible at all.

**Comment by flozano** [comment]
I guess it's related to this... https://github.com/mvel/mvel/commit/42b8ac52a868977b958eab27aff5838a70c826e0

**Comment by flozano** [comment]
Any feedback about this one? I'm forcing an older version of the library in order to keep backward compatibility in existing rules, not sure what will be the way forward...
