### ISSUE TITLE
ASMAccessorImpl_ Growth leads to OOM

### ISSUE THREAD

**Issue by fengkai** [mvel/mvel#299]
I use the method: Object result = MVEL.executeExpression(compiledExpression, Object);

After I started - verbose: class for jvm, I found that 'ASMAccessorImpl_xxxx' class was being generated all the time, which eventually led to the continuous growth of my off heap memory and fullgc.

How can i solve this? Thanks!

Here is stack trace:
     org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer:_initJIT() 

     @org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor()
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95)
        at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
        at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
        at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:35)
        at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
        at org.mvel2.MVEL.executeExpression(MVEL.java:969)

**Comment by MalcolmOdd** [comment]
Normally the ASMAccessorImpl_xxxx is generated only once per node. Can you provide more concrete example of the expression that you're compiling? Are you reusing the same compiled expression or is it a new one each time?

The default evaluation switches to pre-compiled after a certain number of execution. To prevent this and remain in the safe reflective mode, you can call `OptimizerFactory.setDefaultOptimizer(OptimizerFactory.SAFE_REFLECTIVE)` before evaluating expressions, or set the `mvel2.disable.jit` environment variable to true.

**Comment by fengkai** [comment]
I think my usage is wrong, not reusing the same compiled expression.

`while (true) {
            Serializable compiledExpression = MVEL.compileExpression("hasRecallType(259) || hasRecallType(261)");
            for (int i = 0; i < 300; i++) {
                expressionContext.reset(i);
                MVEL.executeExpression(compiledExpression, expressionContext);
            }
            sleep(10);
        }`

**Comment by fengkai** [comment]
If compile the same string every time, can the underlying layer not create ASM class and automatic reuse?

**Comment by MalcolmOdd** [comment]
> If compile the same string every time, can the underlying layer not create ASM class and automatic reuse?

Yeah, there are many ways to do this:
- Deactivate ASM through any of the methods I described in my first comment, for instance by setting `mvel2.disable.jit` to true
- Use MVEL through JSR223
- Use MVEL.eval(String expression, ...) rather than MVEL.executeExpression(...)

**Comment by MalcolmOdd** [comment]
If you don't need to reuse the expression more than once then you could use MVEL.eval(String expression, ...) rather than MVEL.executeExpression(...), or use MVEL through JSR223. Otherwise see my first comment about deactivating ASM through settings.
