### ISSUE TITLE
JDK17 unsupported?

### ISSUE THREAD

**Issue by flozano** [mvel/mvel#309]
I'm getting this when running mvel2/drools with JDK17:
```
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.mvel2.asm.ClassReader.<init>(ClassReader.java:184)
	at org.mvel2.asm.ClassReader.<init>(ClassReader.java:166)
	at org.mvel2.asm.ClassReader.<init>(ClassReader.java:152)
	at org.mvel2.asm.ClassReader.<init>(ClassReader.java:273)
	at org.drools.mvel.asm.ClassFieldInspectorImpl.processClassWithByteCode(ClassFieldInspectorImpl.java:104)
	at org.drools.mvel.asm.ClassFieldInspectorImpl.<init>(ClassFieldInspectorImpl.java:87)
	at org.drools.mvel.MVELCoreComponentsBuilder.createClassFieldInspector(MVELCoreComponentsBuilder.java:59)
	at org.drools.core.base.CoreComponentsBuilder.createClassFieldInspector(CoreComponentsBuilder.java:58)
	at org.drools.core.base.ClassFieldAccessorStore.getClassFieldInspector(ClassFieldAccessorStore.java:298)
	at org.drools.core.base.ClassFieldAccessorStore.getFieldType(ClassFieldAccessorStore.java:282)
	at org.drools.compiler.rule.builder.PatternBuilder.getValueType(PatternBuilder.java:1014)
	at org.drools.compiler.rule.builder.PatternBuilder.normalizeExpression(PatternBuilder.java:982)
	at org.drools.compiler.rule.builder.PatternBuilder.rewriteCompositeExpressions(PatternBuilder.java:953)
	at org.drools.compiler.rule.builder.PatternBuilder.rewriteOrExpressions(PatternBuilder.java:930)
	at org.drools.compiler.rule.builder.PatternBuilder.buildExpression(PatternBuilder.java:911)
	at org.drools.compiler.rule.builder.PatternBuilder.buildCcdDescr(PatternBuilder.java:877)
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:694)
	at org.drools.compiler.rule.builder.PatternBuilder.processConstraintsAndBinds(PatternBuilder.java:598)
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:171)
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:138)
	at org.drools.compiler.rule.builder.PatternBuilder.build(PatternBuilder.java:118)
	at org.drools.compiler.rule.builder.GroupElementBuilder.build(GroupElementBuilder.java:66)
	at org.drools.compiler.rule.builder.RuleBuilder.build(RuleBuilder.java:106)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.internalAddRule(KnowledgeBuilderImpl.java:1113)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.addRule(KnowledgeBuilderImpl.java:1108)
	at org.drools.compiler.builder.impl.KnowledgeBuilderImpl.lambda$compileRulesLevel$3(KnowledgeBuilderImpl.java:1064)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
```
by looking at embedded asm package, it seems latest supported version is V12.

**Comment by MalcolmOdd** [comment]
What version of mvel are you using? Please make sure it's more recent than 2.4.9, which includes the following commit: https://github.com/mvel/mvel/commit/8aa17f8769c2bd52ae98878eaa58eac0df124ee1.
Apart from that, PR #282 would be required for certain expressions to be evaluated in JDK 17+ but it's not merged yet.

**Comment by splatch** [comment]
Some static fields within drools were failing to initialize. By tracing DROOLS-7187 and startup I managed to get mvel and drools up with below JVM options:
```
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.lang.reflect=ALL-UNNAMED
--add-opens=java.base/java.text=ALL-UNNAMED
--add-opens=java.desktop/java.awt.font=ALL-UNNAMED
```

**Comment by damlaYasarr** [comment]
I changed jdk version to 19, then it worked.
