### ISSUE TITLE
new CompileException() with cursor equals to -1 might cause StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ruoyangryan** [mvel/mvel#312]
Hi, my team is currently using the MVEL as a DSL compile engine in our project. During the test process we found our APK crashed strangely caused by a `StringIndexOutOfBoundsException`. After checking out the error log, it seemed like the error happened during the call of the `toString()` method of the `CompileException` class. 

In the method `showCodeNearError(char[] expr, int cursor)`, the attribute `matchStart` was set equal to `cursor`. When this input `cursor` equals to -1, `matchStart` will also be -1, and the call of `new String()` will thus produce an `IndexOutOfBoundsException`. Unfortunately we cannot locate the exact reason why this `cursor` was -1 by our error log. 

This error can be easily reproduced by constructor a new `CompileException` with `cursor` set to -1 and then call its `toString()` method. 

Below is the error log of our APK crash. Due to security reasons it is not full but hope it can produce some insights: 

```
org.mvel2.util.g: java.lang.StringIndexOutOfBoundsException: length=16; index=-1
org.mvel2.util.g: 	at java.lang.String.substring(String.java:2023)
org.mvel2.util.g: 	at org.mvel2.util.g.a(ErrorUtil.java:4)
org.mvel2.util.g: 	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.e(ReflectiveAccessorOptimizer.java:16)
org.mvel2.util.g: 	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.b(ReflectiveAccessorOptimizer.java:8)
org.mvel2.util.g: 	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:12)
org.mvel2.util.g: 	at org.mvel2.ast.ASTNode.a(ASTNode.java:17)
org.mvel2.util.g: 	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:4)
org.mvel2.util.g: 	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:2)
org.mvel2.util.g: 	at org.mvel2.optimizers.impl.refl.a.b.getValue(ExprValueAccessor.java:1)
org.mvel2.util.g: 	at org.mvel2.optimizers.impl.refl.a.e.getValue(MapCreator.java:3)
org.mvel2.util.g: 	at org.mvel2.ast.InlineCollectionNode.getReducedValueAccelerated(InlineCollectionNode.java:2)
org.mvel2.util.g: 	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:1)
org.mvel2.util.g: 	at org.mvel2.ast.AssignmentNode.getReducedValueAccelerated(AssignmentNode.java:6)
org.mvel2.util.g: 	at org.mvel2.f.a(MVELRuntime.java:7)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:1)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:10)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:3)
org.mvel2.util.g: 	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:2)
org.mvel2.util.g: 	at org.mvel2.f.a(MVELRuntime.java:7)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:1)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:10)
org.mvel2.util.g: 	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:3)
org.mvel2.util.g: 	at org.mvel2.ast.ForEachNode.getReducedValue(ForEachNode.java:10)
org.mvel2.util.g: 	at org.mvel2.MVELInterpretedRuntime.c(MVELInterpretedRuntime.java:12)
org.mvel2.util.g: 	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:5)
org.mvel2.util.g: 	at org.mvel2.e.b(MVEL.java:3)
```

And here is another one:

```
java.lang.StringIndexOutOfBoundsException: length=3320; regionStart=-1; regionLength=3321
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:110)
	at org.mvel2.CompileException.a(CompileException.java:11)
	at org.mvel2.CompileException.b(CompileException.java:5)
	at org.mvel2.CompileException.toString(CompileException.java:1)
	at java.lang.Throwable.<init>(Throwable.java:323)
	at java.lang.Exception.<init>(Exception.java:102)
	at java.lang.RuntimeException.<init>(RuntimeException.java:96)
```

**Comment by MalcolmOdd** [comment]
Hi @ruoyangryan ,
Your MVEL code appears to be triggering an error but then the engine is failing to output the cause of the error. Your first stack trace looks similar to #295 and might be fixed by #296 (the faulty access would be bypassed because the array would be null).
Unfortunately this PR is not in a release - @mariofusco, any plan to merge and release fixes?

**Comment by ruoyangryan** [comment]
Hi @MalcolmOdd 
Sorry I cannot provide the full error message. The whole call stack is something like this: our project's code caught the exception during MVEL execution in the outer layer, and called completableFuture.completeExceptionally(). In this method the toString() method of the exception was called and threw this error. So it did not have a chance to print the full error message of MVEL. And since I cannot reproduce this error in the unit test, I have no clue why the cursor might be -1. And I'm not sure whether my problem is the same with #295 since my expression causing this error does not use ternary expressions.
