### ISSUE TITLE
How use try...catch...finally in expression?

### ISSUE THREAD

**Issue by linux2014linux** [mvel/mvel#339]
How should I use try...catch..finally in mvel2 expression?

String expression = "def func() {try { a = 1/0; } catch(Exception e) {return -1;}}";
MVEL.compileExpression(fieldExpression);

Error happen:
```
9月 07, 2023 8:39:52 下午 org.mvel2.util.ErrorUtil rewriteIfNeeded
警告: 
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at org.mvel2.util.ErrorUtil.rewriteIfNeeded(ErrorUtil.java:22)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1295)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:127)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:68)
	at org.mvel2.ast.Function.<init>(Function.java:92)
	at org.mvel2.util.FunctionParser.parse(FunctionParser.java:117)
	at org.mvel2.compiler.AbstractParser._captureBlock(AbstractParser.java:1651)
	at org.mvel2.compiler.AbstractParser.captureCodeBlock(AbstractParser.java:1616)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:487)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:127)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:68)
	at org.mvel2.MVEL.compileExpression(MVEL.java:827)
	at org.mvel2.MVEL.compileExpression(MVEL.java:836)
	at org.mvel2.MVEL.compileExpression(MVEL.java:740)
```

**Comment by MalcolmOdd** [comment]
The exception should have been:
```
[Error: was expecting type: java.lang.Object; but found type: <Unknown>]
```
But the exception was caught and another exception was thrown while trying to reformat it. I made a fix for this in PR #296 but unfortunately the fix was reverted by @mariofusco in commit ffd67dbd8de542a3fae140111b84391ffaf2d125
