### ISSUE TITLE
CompileException on seemingly valid MVEL, adding extra semi-colons resolves exception

### ISSUE THREAD

**Issue by ScottCUSA** [mvel/mvel#342]
Using MVEL 2.5.0 with Java 8 and Java 20 the following minimized MVEL throws a CompileException when passed to `org.mvel2.MVEL.evalToString`.

```MVEL
port = 'ae1'; if (port.contains('-')) {port = port.substring(port.indexOf('-') + 1);} else if (port.startsWith('ae')) {port = port.replace('ae', 'lag-');} port = port.toUpperCase();
```

```
org.mvel2.CompileException: [Error: unexpected token or unknown identifier:port.toUpperCase()]
[Near : {... sWith('ae')) {port = port.replace('ae', 'lag-');} port = port.toUpperCase(); ....}]
                                                               ^
[Line: 1, Column: 156]
	at org.mvel2.MVELInterpretedRuntime.parseAndExecuteInterpreted(MVELInterpretedRuntime.java:149) ~[jaxws-api-2.3.1.jar:?]
	at org.mvel2.MVELInterpretedRuntime.parse(MVELInterpretedRuntime.java:58) ~[jaxws-api-2.3.1.jar:?]
	at org.mvel2.MVEL.eval(MVEL.java:170) ~[jaxws-api-2.3.1.jar:?]
	at org.mvel2.MVEL.evalToString(MVEL.java:349) ~[jaxws-api-2.3.1.jar:?]]
        ...
```

If I add two semi-colons to the end of the if block immediately proceeding the unexpected token it works without issue. 

```
port = 'ae1'; if (port.contains('-')) {port = port.substring(port.indexOf('-') + 1);} else if (port.startsWith('ae')) {port = port.replace('ae', 'lag-');};; port = port.toUpperCase();
```

result = LAG-1

**Comment by ScottCUSA** [comment]
It looks like there's a null value on the stack when it should be empty prior to evaluating the expression `port = port.toUpperCase()`

I think it's because there are two end of END_OF_STMT ASTNodes in the splitAccumulator after the end of the else if code block and the because the stack is empty after the second the parses pushes a null value onto the stack.

**Comment by ScottCUSA** [comment]
Interpreted test fails, compiled test passes:

```java
package org.mvel2.tests.core;

import java.util.HashMap;

import org.mvel2.MVEL;
import org.mvel2.ParserContext;
import org.mvel2.compiler.CompiledExpression;
import org.mvel2.compiler.ExpressionCompiler;
import org.mvel2.integration.impl.CachedMapVariableResolverFactory;

public class TestInterpretedVsCompiled extends AbstractTest{


    public void testInterpreted() {

        HashMap<String, Object> variables = new HashMap<>();
        CachedMapVariableResolverFactory resolverFactory = new CachedMapVariableResolverFactory(variables);

        String expression = "port = 'ae1';\n" +
                        "if (port.contains('-')) {\n" +
                        "    port = port.substring(port.indexOf('-') + 1);\n" +
                        "} else if (port.startsWith('ae')) {\n" +
                        "    port = port.replace('ae', 'lag-');\n" +
                        "}\n" +
                        "port = port.toLowerCase();\n" +
                        "return port;";


        Object result = MVEL.eval(expression, resolverFactory);

        assertEquals("lag-1", result);

    }

    public void testCompiled() {
        ParserContext ctx = new ParserContext();


        HashMap<String, Object> variables = new HashMap<>();
        CachedMapVariableResolverFactory factory = new CachedMapVariableResolverFactory(variables);
        
        String expression = "port = 'ae1';\n" +
                        "if (port.contains('-')) {\n" +
                        "    port = port.substring(port.indexOf('-') + 1);\n" +
                        "} else if (port.startsWith('ae')) {\n" +
                        "    port = port.replace('ae', 'lag-');\n" +
                        "}\n" +
                        "port = port.toLowerCase();\n" +
                        "return port;";

        ExpressionCompiler compiler =
                new ExpressionCompiler(expression, ctx);

        CompiledExpression cp = compiler.compile();
        Object result = MVEL.executeExpression(cp, ctx, factory);

        assertEquals("lag-1", result);

    }
}


```
