### ISSUE TITLE
Don't throw an exception when the data doesn't exist.

### ISSUE THREAD

**Issue by vampireslove** [mvel/mvel#343]
public static void main(String[] args) {
		String expression = "name == 'joy' || age > 10";
		Map<String,Object>  paramMap =new HashMap<>();
		paramMap.put("age", 15);
		CompiledExpression compiledExpression = new ExpressionCompiler(expression).compile();
		Object obj =  MVEL.executeExpression(compiledExpression, paramMap);
		System.out.println(obj);
	}
I expect the result output to be true, but an exception is thrown. Can this situation be optimized, when encountering non-existent data, it should be judged as unsatisfied instead of throwing an exception?

ERROR:
Exception in thread "main" [Error: unresolvable property or identifier: name]
[Near : {... name == 'joy' || age > 10 ....}]
             ^
[Line: 1, Column: 1]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:702)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:364)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:167)
	at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:81)
	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:139)
	at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:113)
	at org.mvel2.MVEL.executeExpression(MVEL.java:984)

**Comment by actuallygaurav** [comment]
Assign this task to me please.

**Comment by vampireslove** [comment]
@actuallygaurav  Thank you, I looked at your solution, but there is a similar issue when the nested value is empty。

**Comment by vampireslove** [comment]
@actuallygaurav Thank you, I looked at your solution, but there is a similar issue when the nested value is empty.	
public static void main(String[] args) {
		   String expression = "name.first == 'joy' || age.num > 10";
		    Map<String,Object> numMap =new HashMap<>();
		    numMap.put("num", 15);
		    Map<String,Object> paramMap =new HashMap<>();
		    paramMap.put("age",numMap);
		    CompiledExpression compiledExpression = new ExpressionCompiler(expression).compile();
		    Object obj =  MVEL.executeExpression(compiledExpression, paramMap);
			System.out.println(obj);
	}
Exception in thread "main" [Error: unresolvable property or identifier: name]
[Near : {... name.first == 'joy' || age.num ....}]
             ^
[Line: 1, Column: 1]
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:702)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:364)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:167)
	at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:81)
	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:139)
	at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:113)
	at org.mvel2.MVEL.executeExpression(MVEL.java:984)

**Comment by vampireslove** [comment]
@actuallygaurav Thank you, I looked at your solution, but there is a similar issue when the nested value is empty.
 public void testOrConditionIfPropertyNotExist() {
    String expression = "name.first == 'joy' || age.num > 10";
    Map<String,Object> numMap =new HashMap<>();
    numMap.put("num", 15);
    Map<String,Object> paramMap =new HashMap<>();
    paramMap.put("age",numMap);
    CompiledExpression compiledExpression = new ExpressionCompiler(expression).compile();
    assertEquals(true, MVEL.executeExpression(compiledExpression, paramMap));
  }
[Error: null pointer: name.first]
[Near : {... name.first == 'joy' || age.num ....}]
             ^
[Line: 1, Column: 1]

	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:454)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:167)
	at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:81)
	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:146)
	at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:34)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:105)
	at org.mvel2.MVEL.executeExpression(MVEL.java:985)
	at org.mvel2.tests.core.CoreConfidenceTests.testOrConditionIfPropertyNotExist(CoreConfidenceTests.java:5062)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.NullPointerException
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:387)
	... 32 more

**Comment by vampireslove** [comment]
@actuallygaurav 
org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer  387 lines
  if (curr == null) throw new NullPointerException();    ->     if (curr == null) break;

Can support cases where nested values are null.

**Comment by vampireslove** [comment]
@actuallygaurav

**Comment by vampireslove** [comment]
@actuallygaurav This situation is also a bit problematic.
public void testOrConditionIfPropertyNotExist() {
    String expression = "name.first.ab.ad.ajh == 'joy' || age.num > 10";
    Map<String,Object> numMap =new HashMap<>();
    numMap.put("num1", 15);
    Map<String,Object> paramMap =new HashMap<>();
    paramMap.put("age",numMap);
    CompiledExpression compiledExpression = new ExpressionCompiler(expression).compile();
    assertEquals(true, MVEL.executeExpression(compiledExpression, paramMap));
  }
[Error: could not access: num; in class: java.util.HashMap]
[Near : {... name.first.ab.ad.ajh == 'joy' || age.num > 10 ....}]
                                              ^
[Line: 1, Column: 34]

	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.getBeanProperty(ReflectiveAccessorOptimizer.java:710)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.compileGetChain(ReflectiveAccessorOptimizer.java:364)
	at org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer.optimizeAccessor(ReflectiveAccessorOptimizer.java:167)
	at org.mvel2.optimizers.dynamic.DynamicOptimizer.optimizeAccessor(DynamicOptimizer.java:81)
	at org.mvel2.ast.ASTNode.optimize(ASTNode.java:159)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:115)
	at org.mvel2.ast.BinaryOperation.getReducedValueAccelerated(BinaryOperation.java:146)
	at org.mvel2.ast.Or.getReducedValueAccelerated(Or.java:35)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:115)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:111)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:105)
	at org.mvel2.MVEL.executeExpression(MVEL.java:985)
	at org.mvel2.tests.core.CoreConfidenceTests.testOrConditionIfPropertyNotExist(CoreConfidenceTests.java:5062)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:177)
	at junit.framework.TestCase.runBare(TestCase.java:142)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:130)
	at junit.framework.TestSuite.runTest(TestSuite.java:241)
	at junit.framework.TestSuite.run(TestSuite.java:236)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)


Process finished with exit code -1

-----------------------------------

org.mvel2.optimizers.impl.refl.ReflectiveAccessorOptimizer 708 lines
throw new PropertyAccessException("could not access: " + property + "; in class: "  + ctx.getClass().getName(), expr, start, pCtx)
=>
LOG.log(Level.WARNING, String.format("could not access property: " + property));
return  null;

**Comment by actuallygaurav** [comment]
@vampireslove : Thanks for highlighting the nested case; I have made the changes to support nested case. Please review it.

**Comment by vampireslove** [comment]
> @vampireslove : Thanks for highlighting the nested case; I have made the changes to support nested case. Please review it.

I verified it and made sure there was no problem. Thanks!

**Comment by MalcolmOdd** [comment]
So if I understand correctly you expect the engine to look at the right-side of a logical expression (`or` or `and`) when the left side fails to evaluate. This is a good idea but unfortunately I believe it would clash with the language specs. On a related note, see the following in node (Javascript):
```
Welcome to Node.js v18.16.0.
Type ".help" for more information.
> age = 15
15
> name == 'joy' || age > 10
Uncaught ReferenceError: name is not defined
> age > 10 || name == 'joy'
true
```

**Comment by vampireslove** [comment]
> So if I understand correctly you expect the engine to look at the right-side of a logical expression (`or` or `and`) when the left side fails to evaluate. This is a good idea but unfortunately I believe it would clash with the language specs. On a related note, see the following in node (Javascript):
> 
> ```
> Welcome to Node.js v18.16.0.
> Type ".help" for more information.
> > age = 15
> 15
> > name == 'joy' || age > 10
> Uncaught ReferenceError: name is not defined
> > age > 10 || name == 'joy'
> true
> ```

The syntax may require this, but in practice this requirement does exist. I only know part of the data, but the engine directly reports an error, and the result I want is that if the data does not exist, it will be treated as if it is not satisfied, and then other conditions will be processed. , instead of throwing an exception directly and terminating other conditional judgments.

**Comment by actuallygaurav** [comment]
@MalcolmOdd so this can be merged or this feature is not required ?

**Comment by MalcolmOdd** [comment]
I'm not a maintainer for this repo so I don't have the ability to approve. 
If I did, I would not approve it at this stage:
- The PR introduces some behaviour discrepancies between the 3 sub-engines (see my comment in #345)
- This would clash with other ecmascript-like languages
- I find it a bit inconsistent. This could also apply for arithmetic operators or within function calls.

I do see value for your purpose so you might decide to fork the library for your projects. However if you do, make sure to cover the cases where the engine decides to switch to the ASM optimizer after ~100 execution of the expression. This behaviour can be deactivated by calling `OptimizerFactory.setDefaultOptimizer(SAFE_REFLECTIVE)`

**Comment by vampireslove** [comment]
@actuallygaurav @MalcolmOdd 
Modify org.mvel2.PropertyAccessor
getBeanProperty method
Number of lines: 682-689
Can support MVEL.eval(expression, paramMap)
After modification：
if (ctx == null) {
LOG.log(Level.WARNING, String.format("unresolvable property or identifier: " + property));
}
else {
LOG.log(Level.WARNING, String.format("could not access property: " + property));
}
return null;

**Comment by kongxiangxin** [comment]
> I'm not a maintainer for this repo so I don't have the ability to approve. If I did, I would not approve it at this stage:
> 
> * The PR introduces some behaviour discrepancies between the 3 sub-engines (see my comment in [Fixed issue #343 - Don't throw an exception when the data doesn't exist !! #345](https://github.com/mvel/mvel/pull/345))
> * This would clash with other ecmascript-like languages
> * I find it a bit inconsistent. This could also apply for arithmetic operators or within function calls.
> 
> I do see value for your purpose so you might decide to fork the library for your projects. However if you do, make sure to cover the cases where the engine decides to switch to the ASM optimizer after ~100 execution of the expression. This behaviour can be deactivated by calling `OptimizerFactory.setDefaultOptimizer(SAFE_REFLECTIVE)`

in javascript, look at this:
`
let a = {};
console.log(a.name == 'aa')
`
it does not throw an exception because a.name  is not an identifier. 

So mvel should not throw exception if we use like this:
`
        Map<String, Object> vars = new HashMap<>();
        Map<String, Object> a = new HashMap<>();
        vars.put("a", a);
        Object eval = MVEL.eval("a.name == 'aa'", vars);
        System.out.println(eval);
`

**Comment by kongxiangxin** [comment]
> > I'm not a maintainer for this repo so I don't have the ability to approve. If I did, I would not approve it at this stage:
> > 
> > * The PR introduces some behaviour discrepancies between the 3 sub-engines (see my comment in [Fixed issue #343 - Don't throw an exception when the data doesn't exist !! #345](https://github.com/mvel/mvel/pull/345))
> > * This would clash with other ecmascript-like languages
> > * I find it a bit inconsistent. This could also apply for arithmetic operators or within function calls.
> > 
> > I do see value for your purpose so you might decide to fork the library for your projects. However if you do, make sure to cover the cases where the engine decides to switch to the ASM optimizer after ~100 execution of the expression. This behaviour can be deactivated by calling `OptimizerFactory.setDefaultOptimizer(SAFE_REFLECTIVE)`
> 
> in javascript, look at this:
> 
> `let a = {}; console.log(a.name == 'aa') `
> 
> it does not throw an exception because a.name is not an identifier.
> 
> So mvel should not throw exception if we use like this:
> 
> ```
>     Map<String, Object> vars = new HashMap<>();
>     Map<String, Object> a = new HashMap<>();
>     vars.put("a", a);
>     Object eval = MVEL.eval("a.name == 'aa'", vars);
>     System.out.println(eval);
> ```

And, why this code throws an exception too? 
``` 
Map<String, Object> vars = new HashMap<>();
Map<String, Object> a = new HashMap<>();
vars.put("a", a);
MVEL.eval("a.name = \"aa\"", vars);
```
Even this:
```       
Map<String, Object> vars = new HashMap<>();
Map<String, Object> a = new HashMap<>();
a.put("name", "bb");
vars.put("a", a);
MVEL.eval("a.name = \"aa\"", vars);
`
I just want put name into the map "a", but it still throws an PropertyAccessException, and even I had set the name key before.

**Comment by MalcolmOdd** [comment]
You raise multiple different cases.
for this one:
```
    Object eval = MVEL.eval("a.name == 'aa'", vars);
``` 
In mvel you would use the square brackets:
```
    Object eval = MVEL.eval("a['name'] == 'aa'", vars);
```
or the question mark/optional operator:
```
    Object eval = MVEL.eval("a.?name == 'aa'", vars);
```
As for the assignments cases, I don't have any opinion on this. maybe it should be supported but it's different from the original issue. However the square bracket notation works in this case.

**Comment by adholland** [comment]
Hi @vampireslove @mariofusco,

Just hit this issue on version 2.4.15.Final when an entry in the map does not exist: -
expression - "val='R'; if (additionalValues.setVisible) {val='D'};val");

[Error: could not access: setVisible; in class: java.util.HashMap]
[Near : {... val='R'; if (additionalValues.setVisible) { ....}]

Wondering if these changes are going to make it into a new release and if so would it resolve my expression? So with the fix I would expect the if statement to be bypassed and return the value 'R'.

Thanks for the time, much appreciated.

**Comment by Jinsist** [comment]
Can I get an attribute that does not exist without reporting an error? Returns null directly, especially for template rendering, Velocity supports returning null

**Comment by vampireslove** [comment]
> Can I get an attribute that does not exist without reporting an error? Returns null directly, especially for template rendering, Velocity supports returning null
> 
> expression sample: String expression = "age + 'is not exist'"; Map<String, Object> variable = new HashMap<>(); variable.put("name", "Jack"); Serializable serializable = MVEL.compileExpression(expression); System.out.println(MVEL.executeExpression(serializable, variable));
> 
> [Error: unresolvable property or identifier: age]

There is a solution, but it was rejected for merging. 
https://github.com/mvel/mvel/pull/345
