### ISSUE TITLE
IllegalArgumentException in org.mvel2.asm.ClassWriter

### ISSUE THREAD

**Issue by lichtin** [mvel/mvel#89]
Getting following exception

Caused by: java.lang.IllegalArgumentException: value 30000
        at org.mvel2.asm.ClassWriter.newConstItem(ClassWriter.java:1057)
        at org.mvel2.asm.MethodWriter.visitLdcInsn(MethodWriter.java:1126)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.getMethod(ASMAccessorOptimizer.java:2084)
        at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:782)
        ... 164 more

apparently caused by the optimizer that kicks in at some point.
The value "30000" is actually a BigDecimal constant in the expression, ie. "30000B".

BigDecimal is not a supported case in the ClassWriter.newConstItem() method.

**Comment by mariofusco** [comment]
Can you please send a reproducer of this problem?

**Comment by lichtin** [comment]
```
  @Test
  public void test_BigDecimal_optimizerSupport() {
    Serializable compiled = MVEL.compileExpression("big = new java.math.BigDecimal(\"10000\"); if (big.compareTo(30000B) > 0) then ;");
    Map<String, Integer> vars = new HashMap<>();
    for (int i = 0; i < 1000; i++) {
      try {
        MVEL.executeExpression(compiled, vars);
      } catch (CompileException e) {
        e.printStackTrace();
        fail("Failed after #executions: " + i);
      }
    }
  }
```

**Comment by postsa** [comment]
Was there ever a resolution to this problem? I believe we are seeing the same issue with version 2.43.

**Comment by postsa** [comment]
A little more info, if we replace the expression 
```
Serializable compiled = MVEL.compileExpression("big = new java.math.BigDecimal(\"10000\"); if (big.compareTo(30000B) > 0) then ;");
```
with one that uses a variable instead of a hardcoded value in compareTo
```
Serializable compiled = MVEL.compileExpression("big = new java.math.BigDecimal(\"10000\"); big2 =  new java.math.BigDecimal(\"30000\"); if (big.compareTo(big2) > 0) then ;");
```
it works.

**Comment by MalcolmOdd** [comment]
I don't know how difficult it is to add BigDecimal in SymbolTable.addConstant(), but wouldn't it make sense if the final else in SymbolTable.addConstant() threw an OptimizationNotSupported instead of an IllegalArgumentException? It would fix issues like this since the engine would keep the constant unoptimized and work with it, and it seems consistent with the intent of the code.
