### ISSUE TITLE
 java.lang.VerifyError: (class: ASMAccessorImpl_8096399931462518849630, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool

### ISSUE THREAD

**Issue by kobe2000** [mvel/mvel#90]
MVEL occasionally throws exception flollowing:

**** COMPILER BUG! REPORT THIS IMMEDIATELY AT http://jira.codehaus.org/browse/mvel2
Expression: item.type

06-May-2016 15:14:09.648 SEVERE [http-apr-8080-exec-4] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [default] in context with path [] threw exception [Filter execution threw an exception] with root cause
 java.lang.VerifyError: (class: ASMAccessorImpl_8096399931462518849630, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:725)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:859)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:243)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:90)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:64)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:922)
	at cn.webwheel.template.TemplateRenderer.output(TemplateRenderer.java:117)
	at cn.webwheel.template.TemplateRenderer.write(TemplateRenderer.java:46)
	at cn.webwheel.template.TemplateRenderer.write(TemplateRenderer.java:110)
	at cn.webwheel.template.TemplateRenderer.write(TemplateRenderer.java:52)
	at cn.webwheel.template.TemplateRenderer.render(TemplateRenderer.java:30)
	at cn.webwheel.results.TemplateResultInterpreter.interpret(TemplateResultInterpreter.java:131)
	at cn.webwheel.results.TemplateResultInterpreter.interpret(TemplateResultInterpreter.java:35)
	at cn.webwheel.Main.interpretResult(Main.java:107)
	at cn.webwheel.Main.process(Main.java:229)
	at cn.webwheel.WebWheelFilter.doFilter(WebWheelFilter.java:78)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)

**Comment by kobe2000** [comment]
It seems to be an old bug fixed in lately version

**Comment by vietj** [comment]
it happens with java 9

```
Caused by: java.lang.VerifyError: (class: ASMAccessorImpl_5103749231506782324530, method: getKnownEgressType signature: ()Ljava/lang/Class;) Illegal type in constant pool
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getConstructor0(Class.java:3315)
	at java.base/java.lang.Class.getConstructor(Class.java:2108)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer._initializeAccessor(ASMAccessorOptimizer.java:753)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.compileAccessor(ASMAccessorOptimizer.java:880)
	at org.mvel2.optimizers.impl.asm.ASMAccessorOptimizer.optimizeAccessor(ASMAccessorOptimizer.java:268)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.optimize(DynamicGetAccessor.java:95)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:65)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:74)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.IfNode.getReducedValueAccelerated(IfNode.java:80)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:106)
	at org.mvel2.ast.ForEachNode.getReducedValueAccelerated(ForEachNode.java:111)
	at org.mvel2.MVELRuntime.execute(MVELRuntime.java:85)
	at org.mvel2.compiler.CompiledExpression.getDirectValue(CompiledExpression.java:123)
	at org.mvel2.compiler.CompiledExpression.getValue(CompiledExpression.java:119)
	at org.mvel2.ast.Function.call(Function.java:165)
	at org.mvel2.ast.PrototypalFunctionInstance.call(PrototypalFunctionInstance.java:18)
	at org.mvel2.optimizers.impl.refl.nodes.FunctionAccessor.getValue(FunctionAccessor.java:49)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:38)
	at org.mvel2.ast.ReturnNode.getReducedValueAccelerated(ReturnNode.java:52)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.ast.Function.call(Function.java:165)
	at org.mvel2.ast.PrototypalFunctionInstance.call(PrototypalFunctionInstance.java:18)
	at org.mvel2.optimizers.impl.refl.nodes.FunctionAccessor.getValue(FunctionAccessor.java:49)
	at org.mvel2.optimizers.dynamic.DynamicGetAccessor.getValue(DynamicGetAccessor.java:78)
	at org.mvel2.ast.ASTNode.getReducedValueAccelerated(ASTNode.java:108)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:929)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:45)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:285)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:247)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:255)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:207)
	at org.mvel2.templates.res.CompiledNamedIncludeNode.eval(CompiledNamedIncludeNode.java:71)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:114)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledIfNode.eval(CompiledIfNode.java:44)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledCodeNode.eval(CompiledCodeNode.java:51)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledForEachNode.eval(CompiledForEachNode.java:128)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledExpressionNode.eval(CompiledExpressionNode.java:46)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CompiledNamedIncludeNode.eval(CompiledNamedIncludeNode.java:71)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledDeclareNode.eval(CompiledDeclareNode.java:55)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledDeclareNode.eval(CompiledDeclareNode.java:55)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TerminalNode.eval(TerminalNode.java:35)
	at org.mvel2.templates.res.CompiledDeclareNode.eval(CompiledDeclareNode.java:55)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.CommentNode.eval(CommentNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.res.TextNode.eval(TextNode.java:42)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:285)
	at org.mvel2.templates.TemplateRuntime.execute(TemplateRuntime.java:247)
	at io.vertx.codegen.Template.render(Template.java:185)
	at io.vertx.codegen.CodeGenProcessor$GeneratedFile.generate(CodeGenProcessor.java:393)
	at io.vertx.codegen.CodeGenProcessor.process(CodeGenProcessor.java:288)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:968)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.access$300(JavacProcessingEnvironment.java:108)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:804)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1204)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1337)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1246)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.handleExceptions(JavacTaskImpl.java:142)
	... 26 more
```
